baseURL = "https://aanthonyl.github.io/portfolio/"
languageCode = 'en-us'
title = 'Anthony Liao'
theme = 'ananke'
enable_extended_parameters = true
canonifyURLs = true

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
Params.custom_css = ["css/custom.css"]
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 2


[menu] 

  [[menu.main]]
  name = "About Me"
  url = "/about/"
  weight = 2

  [[menu.main]]
  name = "Games I've Worked On"
  url = "/games/"
  weight = 3

  [[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 4

  [[menu.main]]
  pre = "<i class='fa-brands fa-linkedin'></i>"
  url = "https://www.linkedin.com/in/anthony-liao-b8a73b189/"
  weight = 6
  Params.icon = "fa-brands fa-linkedin"  # Font Awesome icon class
  Params.external = true
